version: '3.5'

volumes:
  ravendb-volume-data:
  eventstore-volume-data:
  eventstore-volume-logs:

services:
  ravendb:
    container_name: marketplace-ravendb
    image: ravendb/ravendb
    ports:
      - 8080:8080
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"
      - RAVEN_Setup_Mode=None
      - RAVEN_DataDir=RavenData
    volumes:
      - type: volume
        source: ravendb-volume-data
        target: /opt/RavenDB/Server/RavenData

  eventstore:
    container_name: marketplace-eventstore
    image: eventstore/eventstore:20.10.0-bionic
    ports:
        - 2113:2113
        - 1113:1113
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes: 
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
